# Generated by Django 5.2.1 on 2025-05-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_remove_offreemploi_competences_requises_and_more'),
        ('postulation_offre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='authentification.travailleur'),
        ),
    ]
