# Generated by Django 5.2.1 on 2025-05-22 11:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_utilisateur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Utilisateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('est_email_verifie', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('est_administrateur', models.BooleanField(default=False, verbose_name='Est administrateur')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token mis en liste noire')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en liste noire')),
            ],
            options={
                'verbose_name': 'Token en liste noire',
                'verbose_name_plural': 'Tokens en liste noire',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id_employeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name="ID Employeur (lié à l'utilisateur)")),
                ('nom_entreprise', models.CharField(max_length=255, unique=True, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(blank=True, max_length=255, null=True, verbose_name="Secteur d'activité")),
                ('adresse_physique_entreprise', models.CharField(blank=True, max_length=500, null=True, verbose_name="Adresse physique de l'entreprise")),
                ('site_web', models.URLField(blank=True, max_length=500, null=True, verbose_name='Site web')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Logo')),
                ('presentation_entreprise', models.TextField(blank=True, null=True, verbose_name="Présentation de l'entreprise")),
                ('culture_entreprise', models.TextField(blank=True, null=True, verbose_name="Culture de l'entreprise")),
                ('besoins_main_oeuvre_specifiques', models.TextField(blank=True, null=True, verbose_name="Besoins spécifiques en main-d'œuvre")),
                ('informations_contact_recrutement', models.TextField(blank=True, null=True, verbose_name='Informations de contact pour le recrutement')),
                ('est_entreprise_verifiee', models.BooleanField(default=False, verbose_name='Entreprise vérifiée')),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
            },
        ),
        migrations.CreateModel(
            name='Travailleur',
            fields=[
                ('id_travailleur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name="ID Travailleur (lié à l'utilisateur)")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('coordonnees_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordonnées de contact')),
                ('photo_profil_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Photo de profil')),
                ('disponibilite', models.CharField(choices=[('IMMEDIATE', 'Immédiate'), ('SOUS_1_MOIS', 'Sous 1 mois'), ('SOUS_3_MOIS', 'Sous 3 mois'), ('NON_DISPONIBLE', 'Non disponible')], default='NON_DISPONIBLE', max_length=20, verbose_name='Disponibilité')),
                ('preference_geographique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Préférence géographique')),
                ('type_contrat_souhaite', models.JSONField(blank=True, default=list, verbose_name='Types de contrat souhaités (liste)')),
                ('cv_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL CV (PDF)')),
                ('description_profil', models.TextField(blank=True, null=True, verbose_name='Description du profil')),
            ],
            options={
                'verbose_name': 'Travailleur',
                'verbose_name_plural': 'Travailleurs',
            },
        ),
    ]
