# Generated by Django 5.2.1 on 2025-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_employeur_logo_url_employeur_logo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travailleur',
            name='cv_url',
        ),
        migrations.RemoveField(
            model_name='travailleur',
            name='photo_profil_url',
        ),
        migrations.RemoveField(
            model_name='travailleur',
            name='preference_geographique',
        ),
        migrations.AddField(
            model_name='travailleur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV (PDF)'),
        ),
        migrations.AddField(
            model_name='travailleur',
            name='latitude_pref',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='travailleur',
            name='longitude_pref',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='travailleur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
