# Generated by Django 5.2.1 on 2025-05-23 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_travailleur_cv_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travailleur',
            name='coordonnees_contact',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Coordonnées invalides.', regex='^[0-9\\s\\+\\-]+$')], verbose_name='Coordonnées de contact'),
        ),
        migrations.AlterField(
            model_name='travailleur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='travailleur',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Nom invalide.', regex='^[a-zA-ZÀ-ÿ\\s-]+$')], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='travailleur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='travailleur',
            name='prenom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Prénom invalide.', regex='^[a-zA-ZÀ-ÿ\\s-]+$')], verbose_name='Prénom'),
        ),
        migrations.AddConstraint(
            model_name='travailleur',
            constraint=models.CheckConstraint(condition=models.Q(('latitude_pref__gte', -90), ('latitude_pref__lte', 90)), name='latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='travailleur',
            constraint=models.CheckConstraint(condition=models.Q(('longitude_pref__gte', -180), ('longitude_pref__lte', 180)), name='longitude_range'),
        ),
    ]
